name: "EasyPush"

on:
  schedule:
    - cron: "0 16 * * *"  # scheduled at 00:00 (UTC+8) everyday
  workflow_dispatch:

env:
  RUN_ENV: 'prod'
  TZ: 'Asia/Shanghai'

jobs:
  build:
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          # ref: master

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Random sleep
        if: github.event_name == 'schedule'
        run: sleep $(shuf -i 2-7 -n 1)

      - name: Run sign
        env:
          WWAPPSECRET: ${{ secrets.WWAPPSECRET }}
          WWAPPID: ${{ secrets.WWAPPID }}
          WWID: ${{ secrets.WWAPPID }}
          WWUSERID: ${{ secrets.WWUSERID }}
          SCKEY: ${{ secrets.SCKEY }}
          PPTOKEN: ${{ secrets.PPTOKEN }}

        run: |
          random_time=$(($RANDOM % 1))
          echo "等待 ${random_time} 分钟后开始签到"
          for((i=1;i<=${random_time};i++));  
          do
          echo "倒计时:剩余 $[${random_time}-$i] 分钟"
          sleep 1m
          done
           
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt
          
          python3 wecomapp.py
          python3 pushplus.py
          python3 serverchan.py
          python3 beijingtime.py
